// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaqukfylwosrslltqtws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hcXVrZnlsd29zcnNsbHRxdHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTIwNTcsImV4cCI6MjA3MzIyODA1N30.08WNuF6Ljn7rJC9J69Sul2C2wFxfFJwRuK_3LqZ8sS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});